# Neural Network by Scratch

### Importing Numpy and Pandas 

In [1]:
import numpy as np
import pandas as pd

### Loading the Dataset as a Pandas Dataframe

In [2]:
data = pd.read_csv('train.csv')
data.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

### Train and Validation set split
We need to first convert the dataframe into a numpy array and transpose it

In [3]:
data = np.array(data)
m , n = data.shape
print(f'data.shape = {m,n}\n')
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data[1:1000]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:m]

X_train = X_train / 255
print(f'X_train.shape = {X_train.shape}')
print(f'Y_train.shape = {Y_train.shape}')

data.shape = (42000, 785)

X_train.shape = (784, 41000)
Y_train.shape = (41000,)


### Initializing Parameters

In [4]:
def init_params():

    W1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    
    W2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    
    return W1, b1, W2, b2

### ReLu Function

In [5]:
def ReLu(Z):
    return np.maximum(Z,0)

### Softmax Function

In [6]:
def softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))

### Forward Propagation

In [7]:
def forward_prop(W1, b1, W2, b2, X):
    
    Z1 = W1.dot(X) + b1
    A1 = ReLu(Z1)
    
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    
    return Z1, A1, Z2, A2

### Derivative of ReLu

In [8]:
def deriv_relu(Z):
    return Z>0

### One Hot Encoder Function

In [9]:
def one_hot(Y):
    
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    
    return one_hot_Y

### Backward Propagation

In [10]:
def back_prop(Z1, A1, Z2, A2, W2, X, Y):

    m = Y.shape[0]
    
    dZ2 = A2 - one_hot(Y)
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * sum(dZ2)
    
    dZ1 = W2.T.dot(dZ2) * deriv_relu(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * sum(dZ1)
    
    return dW1, db1, dW2, db2

### Update Parameters

In [11]:
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):

    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    
    return W1, b1, W2, b2

### Prediction and Accuracy functions

In [12]:
def make_prediction(A2):
    return np.argmax(A2, 0)

def get_accuracy(Y_hat, Y):
    print(Y_hat, Y)
    return np.sum(Y_hat==Y)/Y.size

### Training Function

In [13]:
def train(X, Y, iterations, alpha):
    
    W1, b1, W2, b2 = init_params()
    
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        
        if (i%10 == 0):
            print(f'Iteration: {i}')
            print(f'Accuracy: {get_accuracy(make_prediction(A2),Y)}')
            
    return W1, b1, W2, b2

In [14]:
train(X_train , Y_train, 500, 0.2)

Iteration: 0
[3 3 3 ... 2 2 3] [4 4 7 ... 8 2 9]
Accuracy: 0.10053658536585366
Iteration: 10
[3 3 7 ... 2 2 3] [4 4 7 ... 8 2 9]
Accuracy: 0.31578048780487805
Iteration: 20
[4 4 7 ... 2 2 3] [4 4 7 ... 8 2 9]
Accuracy: 0.41785365853658535
Iteration: 30
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.506
Iteration: 40
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.572780487804878
Iteration: 50
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.6235121951219512
Iteration: 60
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.6626585365853659
Iteration: 70
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.6939756097560975
Iteration: 80
[9 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.7201951219512195
Iteration: 90
[4 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.7413170731707317
Iteration: 100
[4 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.7588536585365854
Iteration: 110
[4 4 7 ... 8 2 4] [4 4 7 ... 8 2 9]
Accuracy: 0.7744878048780488
Iteration: 120
[4 4 7 ... 8 2 9] [4 4 7 ... 8 2 9]
Accuracy: 0

(array([[-0.05034981, -0.40200817, -0.07435189, ...,  0.46892683,
          0.35541367,  0.2844834 ],
        [ 0.26597116,  0.43589465,  0.12714838, ..., -0.11003386,
         -0.47551874,  0.15927587],
        [ 0.22263857,  0.09772221, -0.19572701, ...,  0.34473877,
         -0.36885053, -0.48539519],
        ...,
        [ 0.23614892, -0.09721041, -0.193387  , ...,  0.19021558,
          0.20598129,  0.28968216],
        [ 0.14456096,  0.10488966,  0.39393864, ...,  0.18323722,
          0.1282891 , -0.34054923],
        [-0.20464646,  0.36820276, -0.34598726, ..., -0.0062111 ,
         -0.25237343, -0.21692149]]),
 array([[-0.02753922, -0.02730228, -0.02738002, ..., -0.02718463,
         -0.02716958, -0.02682872],
        [ 0.16994919,  0.17018613,  0.17010838, ...,  0.17030377,
          0.17031883,  0.17065968],
        [-0.05429363, -0.05405669, -0.05413443, ..., -0.05393904,
         -0.05392399, -0.05358313],
        ...,
        [ 0.46096491,  0.46120184,  0.4611241 , ...,  